---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcure
spec:
  replicas: 1
  selector:
    matchLabels:
      app: healthcure
  template:
    metadata:
      labels:
        app: healthcure
    spec:
      containers:
        - name: healthcure
          image: eranil2u/healthcure:01
          ports:
            - containerPort: 8081
          env:
            - name: PORT
              value: "8081"
---
apiVersion: v1
kind: Service
metadata:
  name: healthcure
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: healthcure
